-- MySQL Script generated by MySQL Workbench
-- Sat Sep 16 16:02:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Fornecedor` (
  `idFornecedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NULL,
  PRIMARY KEY (`idFornecedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL,
  `Local` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente PF`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente PF` (
  `idCliente` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Identificação` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `Identificação_UNIQUE` (`Identificação` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente PJ`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente PJ` (
  `idCliente PJ` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Identificação` VARCHAR(45) NOT NULL,
  `Endereço` VARCHAR(45) NULL,
  `CNPJ` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente PJ`),
  UNIQUE INDEX `Identificação_UNIQUE` (`Identificação` ASC) VISIBLE,
  UNIQUE INDEX `CNPJ_UNIQUE` (`CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL,
  `Endreço` VARCHAR(45) NULL,
  `Status do Pedido` VARCHAR(45) NULL,
  `Código de Rastreio` VARCHAR(45) NULL,
  PRIMARY KEY (`idEntrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status do pedido` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Frete` FLOAT NULL,
  `Cliente PJ_idCliente PJ` INT NOT NULL,
  `Entrega_idEntrega` INT NOT NULL,
  PRIMARY KEY (`idPedido`, `Cliente_idCliente`, `Cliente PJ_idCliente PJ`, `Entrega_idEntrega`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  INDEX `fk_Pedido_Cliente PJ1_idx` (`Cliente PJ_idCliente PJ` ASC) VISIBLE,
  INDEX `fk_Pedido_Entrega1_idx` (`Entrega_idEntrega` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente PF` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente PJ1`
    FOREIGN KEY (`Cliente PJ_idCliente PJ`)
    REFERENCES `mydb`.`Cliente PJ` (`idCliente PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Entrega1`
    FOREIGN KEY (`Entrega_idEntrega`)
    REFERENCES `mydb`.`Entrega` (`idEntrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `idProduto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descrição` VARCHAR(45) NULL,
  `Valor` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto e Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto e Estoque` (
  `Produto_idProduto` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Produto_idProduto`, `Estoque_idEstoque`),
  INDEX `fk_Produto_has_Estoque_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  INDEX `fk_Produto_has_Estoque_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Estoque_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Estoque_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disponibiliza um Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disponibiliza um Produto` (
  `Produto_idProduto` INT NOT NULL,
  `Fornecedor_idFornecedor` INT NOT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Fornecedor_idFornecedor`),
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_idFornecedor` ASC) VISIBLE,
  INDEX `fk_Produto_has_Fornecedor_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornecedor`)
    REFERENCES `mydb`.`Fornecedor` (`idFornecedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Relação de Produto por Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Relação de Produto por Pedido` (
  `Produto_idProduto` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` VARCHAR(45) NULL,
  PRIMARY KEY (`Produto_idProduto`, `Pedido_idPedido`),
  INDEX `fk_Produto_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) VISIBLE,
  INDEX `fk_Produto_has_Pedido_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Pedido_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `mydb`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Terceirro - Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Terceirro - Vendedor` (
  `idTerceirro - Vendedor` INT NOT NULL,
  `Razão Social` VARCHAR(45) NULL,
  `Local` VARCHAR(45) NULL,
  `Terceirro - Vendedorcol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTerceirro - Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos por vendedor (terceiro)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos por vendedor (terceiro)` (
  `Produto_idProduto` INT NOT NULL,
  `Terceirro - Vendedor_idTerceirro - Vendedor` INT NOT NULL,
  `Produtos por vendedorcol` VARCHAR(45) NULL,
  `Quantidade` INT NULL,
  PRIMARY KEY (`Produto_idProduto`, `Terceirro - Vendedor_idTerceirro - Vendedor`),
  INDEX `fk_Produto_has_Terceirro - Vendedor_Terceirro - Vendedor1_idx` (`Terceirro - Vendedor_idTerceirro - Vendedor` ASC) VISIBLE,
  INDEX `fk_Produto_has_Terceirro - Vendedor_Produto1_idx` (`Produto_idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_has_Terceirro - Vendedor_Produto1`
    FOREIGN KEY (`Produto_idProduto`)
    REFERENCES `mydb`.`Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Terceirro - Vendedor_Terceirro - Vendedor1`
    FOREIGN KEY (`Terceirro - Vendedor_idTerceirro - Vendedor`)
    REFERENCES `mydb`.`Terceirro - Vendedor` (`idTerceirro - Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento Via Cartão`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento Via Cartão` (
  `idPagamento` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `Número` INT NULL,
  `Validade` INT NULL,
  `Bandeira` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formas de Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Formas de Pagamento` (
  `idFormas de Pagamento` INT NOT NULL,
  `Cartão` VARCHAR(45) NULL,
  `Boleto` VARCHAR(45) NULL,
  `Pix` VARCHAR(45) NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Pedido_Cliente_idCliente` INT NOT NULL,
  `Pedido_Cliente PJ_idCliente PJ` INT NOT NULL,
  PRIMARY KEY (`idFormas de Pagamento`, `Pedido_idPedido`, `Pedido_Cliente_idCliente`, `Pedido_Cliente PJ_idCliente PJ`),
  INDEX `fk_Formas de Pagamento_Pedido1_idx` (`Pedido_idPedido` ASC, `Pedido_Cliente_idCliente` ASC, `Pedido_Cliente PJ_idCliente PJ` ASC) VISIBLE,
  CONSTRAINT `fk_Formas de Pagamento_Pedido1`
    FOREIGN KEY (`Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Cliente PJ_idCliente PJ`)
    REFERENCES `mydb`.`Pedido` (`idPedido` , `Cliente_idCliente` , `Cliente PJ_idCliente PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento Via Boleto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento Via Boleto` (
  `idPagamento Via Boleto` INT NOT NULL,
  `Número` VARCHAR(45) NULL,
  `Banco` VARCHAR(45) NULL,
  `Pagamento Via Boletocol` VARCHAR(45) NULL,
  `Formas de Pagamento_idFormas de Pagamento` INT NOT NULL,
  `Formas de Pagamento_Pedido_idPedido` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` INT NOT NULL,
  PRIMARY KEY (`idPagamento Via Boleto`, `Formas de Pagamento_idFormas de Pagamento`, `Formas de Pagamento_Pedido_idPedido`, `Formas de Pagamento_Pedido_Cliente_idCliente`, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`),
  INDEX `fk_Pagamento Via Boleto_Formas de Pagamento1_idx` (`Formas de Pagamento_idFormas de Pagamento` ASC, `Formas de Pagamento_Pedido_idPedido` ASC, `Formas de Pagamento_Pedido_Cliente_idCliente` ASC, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento Via Boleto_Formas de Pagamento1`
    FOREIGN KEY (`Formas de Pagamento_idFormas de Pagamento` , `Formas de Pagamento_Pedido_idPedido` , `Formas de Pagamento_Pedido_Cliente_idCliente` , `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`)
    REFERENCES `mydb`.`Formas de Pagamento` (`idFormas de Pagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Cliente PJ_idCliente PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento via Pix`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento via Pix` (
  `idPagamento via Pix` INT NOT NULL,
  `Chave Pix Numérica` INT NULL,
  `Chave Pix Email` VARCHAR(45) NULL,
  `` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento via Pix`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento Via Cartão_has_Formas de Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento Via Cartão_has_Formas de Pagamento` (
  `Pagamento Via Cartão_idPagamento` INT NOT NULL,
  `Formas de Pagamento_idFormas de Pagamento` INT NOT NULL,
  `Formas de Pagamento_Pedido_idPedido` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` INT NOT NULL,
  PRIMARY KEY (`Pagamento Via Cartão_idPagamento`, `Formas de Pagamento_idFormas de Pagamento`, `Formas de Pagamento_Pedido_idPedido`, `Formas de Pagamento_Pedido_Cliente_idCliente`, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`),
  INDEX `fk_Pagamento Via Cartão_has_Formas de Pagamento_Formas de _idx` (`Formas de Pagamento_idFormas de Pagamento` ASC, `Formas de Pagamento_Pedido_idPedido` ASC, `Formas de Pagamento_Pedido_Cliente_idCliente` ASC, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` ASC) VISIBLE,
  INDEX `fk_Pagamento Via Cartão_has_Formas de Pagamento_Pagamento _idx` (`Pagamento Via Cartão_idPagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento Via Cartão_has_Formas de Pagamento_Pagamento Vi1`
    FOREIGN KEY (`Pagamento Via Cartão_idPagamento`)
    REFERENCES `mydb`.`Pagamento Via Cartão` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento Via Cartão_has_Formas de Pagamento_Formas de Pa1`
    FOREIGN KEY (`Formas de Pagamento_idFormas de Pagamento` , `Formas de Pagamento_Pedido_idPedido` , `Formas de Pagamento_Pedido_Cliente_idCliente` , `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`)
    REFERENCES `mydb`.`Formas de Pagamento` (`idFormas de Pagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Cliente PJ_idCliente PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pagamento via Pix_has_Formas de Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pagamento via Pix_has_Formas de Pagamento` (
  `Pagamento via Pix_idPagamento via Pix` INT NOT NULL,
  `Formas de Pagamento_idFormas de Pagamento` INT NOT NULL,
  `Formas de Pagamento_Pedido_idPedido` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente_idCliente` INT NOT NULL,
  `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` INT NOT NULL,
  PRIMARY KEY (`Pagamento via Pix_idPagamento via Pix`, `Formas de Pagamento_idFormas de Pagamento`, `Formas de Pagamento_Pedido_idPedido`, `Formas de Pagamento_Pedido_Cliente_idCliente`, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`),
  INDEX `fk_Pagamento via Pix_has_Formas de Pagamento_Formas de Paga_idx` (`Formas de Pagamento_idFormas de Pagamento` ASC, `Formas de Pagamento_Pedido_idPedido` ASC, `Formas de Pagamento_Pedido_Cliente_idCliente` ASC, `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ` ASC) VISIBLE,
  INDEX `fk_Pagamento via Pix_has_Formas de Pagamento_Pagamento via _idx` (`Pagamento via Pix_idPagamento via Pix` ASC) VISIBLE,
  CONSTRAINT `fk_Pagamento via Pix_has_Formas de Pagamento_Pagamento via Pix1`
    FOREIGN KEY (`Pagamento via Pix_idPagamento via Pix`)
    REFERENCES `mydb`.`Pagamento via Pix` (`idPagamento via Pix`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagamento via Pix_has_Formas de Pagamento_Formas de Pagame1`
    FOREIGN KEY (`Formas de Pagamento_idFormas de Pagamento` , `Formas de Pagamento_Pedido_idPedido` , `Formas de Pagamento_Pedido_Cliente_idCliente` , `Formas de Pagamento_Pedido_Cliente PJ_idCliente PJ`)
    REFERENCES `mydb`.`Formas de Pagamento` (`idFormas de Pagamento` , `Pedido_idPedido` , `Pedido_Cliente_idCliente` , `Pedido_Cliente PJ_idCliente PJ`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
